name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '13'
          postgresql db: ${{ secrets.PGDATABASE }}
          postgresql user: ${{ secrets.PGUSERNAME }}
          postgresql password: ${{ secrets.PGPASSWORD }}
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn migrate up
          start: yarn dev
        env:
          PGHOST: localhost
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGUSERNAME: ${{ secrets.PGUSERNAME }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          CSRF_TOKEN_SECRET: ${{ secrets.CSRF_TOKEN_SECRET }}
